public class CaseRequestWrapper extends BaseRequestWrapper {
    public String subject;
    public String description;
    public String status;
    public String priority;
    public String origin;
    public String type;
    public String reason;
    public String suppliedName;
    public String suppliedEmail;
    public String suppliedPhone;
    public String suppliedCompany;
    public String accountId;
    public String contactId;
}
